version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=iamdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    volumes:
      - ./.env:/root/.env:ro
    networks:
      - idmapp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  react-app:
    build:
      context: ../../IDMReactClient
      args:
        REACT_APP_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - app
    networks:
      - idmapp-network
    restart: unless-stopped

networks:
  idmapp-network:
    driver: bridge 