version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-iamdb}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      
      # Server Configuration
      - SERVER_PORT=${SERVER_PORT:-8080}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # Logging Configuration
      - FLUENT_ENABLED=${FLUENT_ENABLED:-false}
      - FLUENT_ENDPOINT=${FLUENT_ENDPOINT:-http://localhost:24224}
      
      # OpenFGA Configuration
      - OPENFGA_API_URL=${OPENFGA_API_URL:-http://localhost:8080}
      - OPENFGA_STORE_ID=${OPENFGA_STORE_ID}
      - OPENFGA_API_TOKEN=${OPENFGA_API_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge 